### PR TITLE
Auth notification and popup

### PR DESCRIPTION
**Pull request by ex47**
hope it helps

### CODE REVIEW

**Comment by alexesprit** [comment]
Hi!

First of all, thanks for PR!

Showing popup notifications (`Notifications.showAuthenticate`) is annoying because of ton of auth errors. It's enough to notify user by showing another icon in the extension toolbar. It's already done.

The popup is almost that what David wants to see. The difference is that you placed the reauth button in the popup window. He suggested a link to the same button in the extension settings (see david-sabata/web-scrobbler#900):
> The popup may then contain the message about the need to reauthenticate and maybe a link to settings page. I wouldn't authenticate users directly from the popup as it is unloaded and destroyed once it loses focus.

It's not hard to add the link to options page. But it's not enough.  Options page has collapsed "Options" sections, and we need to expand it somehow and to scroll to reauth button on clicking by reauth link in the popup window. Otherwise, users won't see this button. That's what I wanted to do, but I don't know how. Have you any ideas?

I don't know why it's important to have the link to optons page, not the reauth button. I tested this PR, and reauth works well by clicking on the button in the popup window. And this way is faster than going to options by clicking on the link and press the button in options page. Maybe we'll have some issues, if we'll use this way of reauth.

Anyway, if we can't find a solution, I will merge your changes and will propose a PR to upstream. It's exactly better than we have now (and we have nothing now).

**Comment by ex47** [comment]
screenshot_10

**Comment by alexesprit** [comment]
Hm, looks nice! I'll test it soon.

**Comment by ex47** [comment]
```
			function auth (authUrlGetter) {
				var onHaveAuthUrl = function(authUrl) {
				chrome.tabs.create({ url: authUrl });
				};

				authUrlGetter(onHaveAuthUrl);
			}

			auth(LastFM.getAuthUrl);
```

And if you know how to simplify this mess, please tell.

**Comment by alexesprit** [comment]
Try this:
```js
function reAuthenticate(tab) {
    console.log('Page action clicked in tab ' + tab);

    LastFM.getAuthUrl(function(authUrl) {
        chrome.tabs.create({ url: authUrl });
    });
}
```
I tested your code; the Last.fm auth page is opened twice on the icon click. My one works well for me.

In Web scrobbler Last.fm page is opened in a separate window, not in a tab:
```js
window.open(authUrl, 'scrobbler-auth');
```

There's no difference how to open that page, but I think it should be the same in every place.

**Comment by alexesprit** [comment]
Is there anything you would like to add to this PR? Or is it ready to be merged?

**Comment by ex47** [comment]
Well, it looks good to me. Maybe we'll run into some conflicts when you update your base branch, it's pretty outdated.

**Pull request merged**
